In [2]:
import numpy as np
import pandas as pd

In [3]:
enterobacteriaceae_bacteria = [
    'Normal E.coli',
    'EHEC or EIEC',
    'Shigella',
    'Klebsiella pneumoniae',
    'Klebsiella oxytoca',
    'Enterobacter',
    'Serratia',
    'Proteus mirabilis',
    'Proteus vulgaris',
    'Providencia',
    'Morganella',
    'Salmonella typhi',
    'Salmonella paratyphi A',
    'Salmonella paratyphi other groups',
    'Salmonella arizona',
    'Edwardsiella',
    'Citrobacter freundii',
    'Citrobacter diversus'
]

In [4]:
nfb_bacteria = [
    'Pseudomonas aeruginosa',
    'Alcaligenes faecalis',
    'Burkholderia cepacia',
    'Cryseobacterium meningosepticum',
    'Moraxella catarrhalis',
    'Moraxella lacunata',
    'Shewanella putrefaciens',
    'Acinetobacter baumannii',
    'Acinetobacter lwoffii',
    'Stenotrophomonas maltophilia',
]

In [5]:
gram_positive_bacteria = [
    'Micrococcus',
    'Staphylococcus areus',
    'Staphylococcus epidermidis',
    'Staphylococcus saprophyticus',
    'Streptococcus pyogenes (group A)',
    'Streptococcus agalactiae (group B)',
    'Streptococcus pneumoniae',
    'Streptococcus viridians',
    'Enterococcus',
    'Non-Enterococcus'
]

In [6]:
enterobacteriaceae_bacteria_tests = pd.DataFrame({
    'Oxidase': ['-', '-', '-', '-', '-',
                '-', '-', '-', '-', '-',
                '-', '-', '-', '-', '-',
                '-', '-', '-'],
    'TSI': ['A/A', 'K/A', 'K/A', 'A/A', 'A/A',
            'A/A', 'A/A', 'K/A', 'A/A', 'K/A',
            'K/A', 'K/A', 'K/A', 'K/A', 'K/A',
            'K/A', 'A/A or K/A', 'A/A'],
    'OF': 'F+',
    'Urease': ['-', '-', '-', '+', '-',
               '-', '-', '+', '+', '+',
               '+', '-', '-', '-', '-',
               '-', '-', '-'],
    'PD': ['-', '-', '-', '-', '-',
               '-', '-', '+', '+', '+',
               '+', '-', '-', '-', '-',
               '-', '-', '-'],
    'IMViC': ['++--',
              '++--',
              '-+--',
              '--++',
              '+-++',
              '--++',
              '--++',
              '-+vv',
              '++vv',
              '++vv',
              '++vv',
              '-+vv',
              '-+vv',
              '-+vv',
              '-+vv',
              '++-+',
              '-+-+',
              '++++'],
    'Motility': ['+', '+', '-', '-', '-',
                 '+', '+', '+', '+', '+',
                 '+', '+', '+', '+', '+',
                 '+', '+', '+'],
    'H2S': ['-', '-', '-', '-', '-',
            '-', '-', '+', '+', '+',
            '-', '+', '-', '+', '+',
            '+', '+', '-'],
    'LDC': ['+', '+', '-', 'NI', 'NI',
            'NI', 'NI', 'NI', 'NI', 'NI',
            'NI', '+', '+', '+', '+',
            '+', '-', '-'],
    'ONPG': ['NI', '+', '-', 'NI', 'NI',
             'NI', '-', 'NI', 'NI', 'NI',
             'NI', 'NI', 'NI', 'NI', 'NI',
             'NI', '+', '+']
}, index=enterobacteriaceae_bacteria)

In [7]:
enterobacteriaceae_bacteria_tests

,Oxidase,TSI,OF,Urease,PD,IMViC,Motility,H2S,LDC,ONPG
Normal E.coli,-,A/A,F+,-,-,++--,+,-,+,NI
EHEC or EIEC,-,K/A,F+,-,-,++--,+,-,+,+
Shigella,-,K/A,F+,-,-,-+--,-,-,-,-
Klebsiella pneumoniae,-,A/A,F+,+,-,--++,-,-,NI,NI
Klebsiella oxytoca,-,A/A,F+,-,-,+-++,-,-,NI,NI
Enterobacter,-,A/A,F+,-,-,--++,+,-,NI,NI
Serratia,-,A/A,F+,-,-,--++,+,-,NI,-
Proteus mirabilis,-,K/A,F+,+,+,-+vv,+,+,NI,NI
Proteus vulgaris,-,A/A,F+,+,+,++vv,+,+,NI,NI
Providencia,-,K/A,F+,+,+,++vv,+,+,NI,NI
Morganella,-,K/A,F+,+,+,++vv,+,-,NI,NI
Salmonella typhi,-,K/A,F+,-,-,-+vv,+,+,+,NI
Salmonella paratyphi A,-,K/A,F+,-,-,-+vv,+,-,+,NI
Salmonella paratyphi other groups,-,K/A,F+,-,-,-+vv,+,+,+,NI
Salmonella arizona,-,K/A,F+,-,-,-+vv,+,+,+,NI
Edwardsiella,-,K/A,F+,-,-,++-+,+,+,+,NI
Citrobacter freundii,-,A/A or K/A,F+,-,-,-+-+,+,+,-,+
Citrobacter diversus,-,A/A,F+,-,-,++++,+,-,-,+

In [8]:
enterobacteriaceae_bacteria_tests.style.set_properties(
    subset=['Oxidase', 'Urease', 'PD', 'IMViC',
            'Motility', 'H2S', 'LDC', 'ONPG'],
    **{'text-align': 'center'}
)

In [9]:
nfb_bacteria

['Pseudomonas aeruginosa',
 'Alcaligenes faecalis',
 'Burkholderia cepacia',
 'Cryseobacterium meningosepticum',
 'Moraxella catarrhalis',
 'Moraxella lacunata',
 'Shewanella putrefaciens',
 'Acinetobacter baumannii',
 'Acinetobacter lwoffii',
 'Stenotrophomonas maltophilia']

In [10]:
nfb_bacteria_tests = pd.DataFrame({
    'Oxidase': ['+', '+', '+', '+', '+',
                '+', '+', '-', '-', '-'],
    'TSI': 'K/K',
    'OF': ['O+', 'NR', 'O+', 'O+', 'NR',
           'NR', 'O+', 'O+', 'NR', 'NR'],
    'Urease': '-',
    'PD': '-',
    'IMViC': ['-+v+',
              '-+v+',
              '-+v+',
              '++v-',
              '-+v-',
              '-+v-',
              '-+v-',
              '-+vv',
              '-+vv',
              '-+v+'],
    'Motility': ['+', '+', '+', '-', '-',
                '-', '+', '-', '-', '-'],
    'H2S': ['-', '-', '-', '-', '-',
            '-', '+', '-', '-', '-'],
    'LDC': 'NI',
    'ONPG': 'NI'
}, index=nfb_bacteria)

nfb_bacteria_tests

,Oxidase,TSI,OF,Urease,PD,IMViC,Motility,H2S,LDC,ONPG
Pseudomonas aeruginosa,+,K/K,O+,-,-,-+v+,+,-,NI,NI
Alcaligenes faecalis,+,K/K,NR,-,-,-+v+,+,-,NI,NI
Burkholderia cepacia,+,K/K,O+,-,-,-+v+,+,-,NI,NI
Cryseobacterium meningosepticum,+,K/K,O+,-,-,++v-,-,-,NI,NI
Moraxella catarrhalis,+,K/K,NR,-,-,-+v-,-,-,NI,NI
Moraxella lacunata,+,K/K,NR,-,-,-+v-,-,-,NI,NI
Shewanella putrefaciens,+,K/K,O+,-,-,-+v-,+,+,NI,NI
Acinetobacter baumannii,-,K/K,O+,-,-,-+vv,-,-,NI,NI
Acinetobacter lwoffii,-,K/K,NR,-,-,-+vv,-,-,NI,NI
Stenotrophomonas maltophilia,-,K/K,NR,-,-,-+v+,-,-,NI,NI

In [11]:
nfb_bacteria_tests.loc['Burkholderia cepacia', 'LDC'] = '+'
nfb_bacteria_tests.loc['Stenotrophomonas maltophilia', 'LDC'] = '+'
nfb_bacteria_tests

,Oxidase,TSI,OF,Urease,PD,IMViC,Motility,H2S,LDC,ONPG
Pseudomonas aeruginosa,+,K/K,O+,-,-,-+v+,+,-,NI,NI
Alcaligenes faecalis,+,K/K,NR,-,-,-+v+,+,-,NI,NI
Burkholderia cepacia,+,K/K,O+,-,-,-+v+,+,-,+,NI
Cryseobacterium meningosepticum,+,K/K,O+,-,-,++v-,-,-,NI,NI
Moraxella catarrhalis,+,K/K,NR,-,-,-+v-,-,-,NI,NI
Moraxella lacunata,+,K/K,NR,-,-,-+v-,-,-,NI,NI
Shewanella putrefaciens,+,K/K,O+,-,-,-+v-,+,+,NI,NI
Acinetobacter baumannii,-,K/K,O+,-,-,-+vv,-,-,NI,NI
Acinetobacter lwoffii,-,K/K,NR,-,-,-+vv,-,-,NI,NI
Stenotrophomonas maltophilia,-,K/K,NR,-,-,-+v+,-,-,+,NI

In [12]:
enterobacteriaceae_bacteria_tests

,Oxidase,TSI,OF,Urease,PD,IMViC,Motility,H2S,LDC,ONPG
Normal E.coli,-,A/A,F+,-,-,++--,+,-,+,NI
EHEC or EIEC,-,K/A,F+,-,-,++--,+,-,+,+
Shigella,-,K/A,F+,-,-,-+--,-,-,-,-
Klebsiella pneumoniae,-,A/A,F+,+,-,--++,-,-,NI,NI
Klebsiella oxytoca,-,A/A,F+,-,-,+-++,-,-,NI,NI
Enterobacter,-,A/A,F+,-,-,--++,+,-,NI,NI
Serratia,-,A/A,F+,-,-,--++,+,-,NI,-
Proteus mirabilis,-,K/A,F+,+,+,-+vv,+,+,NI,NI
Proteus vulgaris,-,A/A,F+,+,+,++vv,+,+,NI,NI
Providencia,-,K/A,F+,+,+,++vv,+,+,NI,NI
Morganella,-,K/A,F+,+,+,++vv,+,-,NI,NI
Salmonella typhi,-,K/A,F+,-,-,-+vv,+,+,+,NI
Salmonella paratyphi A,-,K/A,F+,-,-,-+vv,+,-,+,NI
Salmonella paratyphi other groups,-,K/A,F+,-,-,-+vv,+,+,+,NI
Salmonella arizona,-,K/A,F+,-,-,-+vv,+,+,+,NI
Edwardsiella,-,K/A,F+,-,-,++-+,+,+,+,NI
Citrobacter freundii,-,A/A or K/A,F+,-,-,-+-+,+,+,-,+
Citrobacter diversus,-,A/A,F+,-,-,++++,+,-,-,+

In [13]:
nfb_bacteria_tests

,Oxidase,TSI,OF,Urease,PD,IMViC,Motility,H2S,LDC,ONPG
Pseudomonas aeruginosa,+,K/K,O+,-,-,-+v+,+,-,NI,NI
Alcaligenes faecalis,+,K/K,NR,-,-,-+v+,+,-,NI,NI
Burkholderia cepacia,+,K/K,O+,-,-,-+v+,+,-,+,NI
Cryseobacterium meningosepticum,+,K/K,O+,-,-,++v-,-,-,NI,NI
Moraxella catarrhalis,+,K/K,NR,-,-,-+v-,-,-,NI,NI
Moraxella lacunata,+,K/K,NR,-,-,-+v-,-,-,NI,NI
Shewanella putrefaciens,+,K/K,O+,-,-,-+v-,+,+,NI,NI
Acinetobacter baumannii,-,K/K,O+,-,-,-+vv,-,-,NI,NI
Acinetobacter lwoffii,-,K/K,NR,-,-,-+vv,-,-,NI,NI
Stenotrophomonas maltophilia,-,K/K,NR,-,-,-+v+,-,-,+,NI

In [14]:
gram_negative_bacteria_chart = pd.concat([enterobacteriaceae_bacteria_tests, nfb_bacteria_tests])
gram_negative_bacteria_chart

,Oxidase,TSI,OF,Urease,PD,IMViC,Motility,H2S,LDC,ONPG
Normal E.coli,-,A/A,F+,-,-,++--,+,-,+,NI
EHEC or EIEC,-,K/A,F+,-,-,++--,+,-,+,+
Shigella,-,K/A,F+,-,-,-+--,-,-,-,-
Klebsiella pneumoniae,-,A/A,F+,+,-,--++,-,-,NI,NI
Klebsiella oxytoca,-,A/A,F+,-,-,+-++,-,-,NI,NI
Enterobacter,-,A/A,F+,-,-,--++,+,-,NI,NI
Serratia,-,A/A,F+,-,-,--++,+,-,NI,-
Proteus mirabilis,-,K/A,F+,+,+,-+vv,+,+,NI,NI
Proteus vulgaris,-,A/A,F+,+,+,++vv,+,+,NI,NI
Providencia,-,K/A,F+,+,+,++vv,+,+,NI,NI
Morganella,-,K/A,F+,+,+,++vv,+,-,NI,NI
Salmonella typhi,-,K/A,F+,-,-,-+vv,+,+,+,NI
Salmonella paratyphi A,-,K/A,F+,-,-,-+vv,+,-,+,NI
Salmonella paratyphi other groups,-,K/A,F+,-,-,-+vv,+,+,+,NI
Salmonella arizona,-,K/A,F+,-,-,-+vv,+,+,+,NI
Edwardsiella,-,K/A,F+,-,-,++-+,+,+,+,NI
Citrobacter freundii,-,A/A or K/A,F+,-,-,-+-+,+,+,-,+
Citrobacter diversus,-,A/A,F+,-,-,++++,+,-,-,+
Pseudomonas aeruginosa,+,K/K,O+,-,-,-+v+,+,-,NI,NI
Alcaligenes faecalis,+,K/K,NR,-,-,-+v+,+,-,NI,NI
Burkholderia cepacia,+,K/K,O+,-,-,-+v+,+,-,+,NI
Cryseobacterium meningosepticum,+,K/K,O+,-,-,++v-,-,-,NI,NI
Moraxella catarrhalis,+,K/K,NR,-,-,-+v-,-,-,NI,NI
Moraxella lacunata,+,K/K,NR,-,-,-+v-,-,-,NI,NI
Shewanella putrefaciens,+,K/K,O+,-,-,-+v-,+,+,NI,NI
Acinetobacter baumannii,-,K/K,O+,-,-,-+vv,-,-,NI,NI
Acinetobacter lwoffii,-,K/K,NR,-,-,-+vv,-,-,NI,NI
Stenotrophomonas maltophilia,-,K/K,NR,-,-,-+v+,-,-,+,NI

In [15]:
enterobacteriaceae_bacteria_tests.index.name = 'Bacteria'
nfb_bacteria_tests.index.name = 'Bacteria'
gram_negative_bacteria_chart.index.name = 'Bacteria'

In [16]:
enterobacteriaceae_bacteria_tests

,Oxidase,TSI,OF,Urease,PD,IMViC,Motility,H2S,LDC,ONPG
Bacteria,,,,,,,,,,
Normal E.coli,-,A/A,F+,-,-,++--,+,-,+,NI
EHEC or EIEC,-,K/A,F+,-,-,++--,+,-,+,+
Shigella,-,K/A,F+,-,-,-+--,-,-,-,-
Klebsiella pneumoniae,-,A/A,F+,+,-,--++,-,-,NI,NI
Klebsiella oxytoca,-,A/A,F+,-,-,+-++,-,-,NI,NI
Enterobacter,-,A/A,F+,-,-,--++,+,-,NI,NI
Serratia,-,A/A,F+,-,-,--++,+,-,NI,-
Proteus mirabilis,-,K/A,F+,+,+,-+vv,+,+,NI,NI
Proteus vulgaris,-,A/A,F+,+,+,++vv,+,+,NI,NI
Providencia,-,K/A,F+,+,+,++vv,+,+,NI,NI
Morganella,-,K/A,F+,+,+,++vv,+,-,NI,NI
Salmonella typhi,-,K/A,F+,-,-,-+vv,+,+,+,NI
Salmonella paratyphi A,-,K/A,F+,-,-,-+vv,+,-,+,NI
Salmonella paratyphi other groups,-,K/A,F+,-,-,-+vv,+,+,+,NI
Salmonella arizona,-,K/A,F+,-,-,-+vv,+,+,+,NI
Edwardsiella,-,K/A,F+,-,-,++-+,+,+,+,NI
Citrobacter freundii,-,A/A or K/A,F+,-,-,-+-+,+,+,-,+
Citrobacter diversus,-,A/A,F+,-,-,++++,+,-,-,+

In [17]:
nfb_bacteria_tests

,Oxidase,TSI,OF,Urease,PD,IMViC,Motility,H2S,LDC,ONPG
Bacteria,,,,,,,,,,
Pseudomonas aeruginosa,+,K/K,O+,-,-,-+v+,+,-,NI,NI
Alcaligenes faecalis,+,K/K,NR,-,-,-+v+,+,-,NI,NI
Burkholderia cepacia,+,K/K,O+,-,-,-+v+,+,-,+,NI
Cryseobacterium meningosepticum,+,K/K,O+,-,-,++v-,-,-,NI,NI
Moraxella catarrhalis,+,K/K,NR,-,-,-+v-,-,-,NI,NI
Moraxella lacunata,+,K/K,NR,-,-,-+v-,-,-,NI,NI
Shewanella putrefaciens,+,K/K,O+,-,-,-+v-,+,+,NI,NI
Acinetobacter baumannii,-,K/K,O+,-,-,-+vv,-,-,NI,NI
Acinetobacter lwoffii,-,K/K,NR,-,-,-+vv,-,-,NI,NI
Stenotrophomonas maltophilia,-,K/K,NR,-,-,-+v+,-,-,+,NI

In [18]:
gram_negative_bacteria_chart

,Oxidase,TSI,OF,Urease,PD,IMViC,Motility,H2S,LDC,ONPG
Bacteria,,,,,,,,,,
Normal E.coli,-,A/A,F+,-,-,++--,+,-,+,NI
EHEC or EIEC,-,K/A,F+,-,-,++--,+,-,+,+
Shigella,-,K/A,F+,-,-,-+--,-,-,-,-
Klebsiella pneumoniae,-,A/A,F+,+,-,--++,-,-,NI,NI
Klebsiella oxytoca,-,A/A,F+,-,-,+-++,-,-,NI,NI
Enterobacter,-,A/A,F+,-,-,--++,+,-,NI,NI
Serratia,-,A/A,F+,-,-,--++,+,-,NI,-
Proteus mirabilis,-,K/A,F+,+,+,-+vv,+,+,NI,NI
Proteus vulgaris,-,A/A,F+,+,+,++vv,+,+,NI,NI
Providencia,-,K/A,F+,+,+,++vv,+,+,NI,NI
Morganella,-,K/A,F+,+,+,++vv,+,-,NI,NI
Salmonella typhi,-,K/A,F+,-,-,-+vv,+,+,+,NI
Salmonella paratyphi A,-,K/A,F+,-,-,-+vv,+,-,+,NI
Salmonella paratyphi other groups,-,K/A,F+,-,-,-+vv,+,+,+,NI
Salmonella arizona,-,K/A,F+,-,-,-+vv,+,+,+,NI
Edwardsiella,-,K/A,F+,-,-,++-+,+,+,+,NI
Citrobacter freundii,-,A/A or K/A,F+,-,-,-+-+,+,+,-,+
Citrobacter diversus,-,A/A,F+,-,-,++++,+,-,-,+
Pseudomonas aeruginosa,+,K/K,O+,-,-,-+v+,+,-,NI,NI
Alcaligenes faecalis,+,K/K,NR,-,-,-+v+,+,-,NI,NI
Burkholderia cepacia,+,K/K,O+,-,-,-+v+,+,-,+,NI
Cryseobacterium meningosepticum,+,K/K,O+,-,-,++v-,-,-,NI,NI
Moraxella catarrhalis,+,K/K,NR,-,-,-+v-,-,-,NI,NI
Moraxella lacunata,+,K/K,NR,-,-,-+v-,-,-,NI,NI
Shewanella putrefaciens,+,K/K,O+,-,-,-+v-,+,+,NI,NI
Acinetobacter baumannii,-,K/K,O+,-,-,-+vv,-,-,NI,NI
Acinetobacter lwoffii,-,K/K,NR,-,-,-+vv,-,-,NI,NI
Stenotrophomonas maltophilia,-,K/K,NR,-,-,-+v+,-,-,+,NI